name = "verifei"
main = "src/worker.ts"
compatibility_date = "2023-09-28"
compatibility_flags = ["nodejs_compat"]

[vars]
SMTP_HELO_DOMAIN = "example.com"
PROBE_EMAIL = "probe@example.com"
MAX_CONCURRENCY_PER_MX = "5"
SMTP_TIMEOUT_MS = "5000"
GRAY_RETRY_AFTER_SEC = "3600"

[[kv_namespaces]]
binding = "EMAIL_BLOCKLIST"
id = "0e50c0b8663943dfac472d176bd52c9f"

[[d1_databases]]
binding = "DB"
database_name = "email_verifei"
database_id = "52655c6e-ba4d-4783-b0d7-b40b8dfaed15"

[[durable_objects.bindings]]
name = "VERIFEI"
class_name = "VerifeiDO"

[[migrations]]
tag = "v1"
new_classes = ["VerifeiDO"]

[[queues.producers]]
queue = "verifei-jobs"
binding = "VERIFICATION_QUEUE"

[[queues.consumers]]
queue = "verifei-jobs"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

[triggers]
crons = ["0 0 * * *"] # Daily cron to sync blocklists from R2 to KV 